#!/usr/bin/perl -w

# Generate usys.S, the stubs for syscalls.

print "# generated by usys.pl - do not edit\n";

print "#include \"kernel/syscall.h\"\n";

sub entry {
    my $name = shift;
    print ".global $name\n";
    print "${name}:\n";
    print " li a7, SYS_${name}\n";
    print " ecall\n";
    print " ret\n";
}
	
entry("fork");
entry("exit");
entry("wait");
entry("pipe");
entry("read");
entry("write");
entry("close");
entry("kill");
entry("exec");
entry("open");
entry("mknod");
entry("unlink");
entry("fstat");
entry("link");
entry("mkdir");
entry("chdir");
entry("dup");
entry("getpid");
entry("sbrk");
entry("sleep");
entry("uptime");
entry("numprocs");
entry("traceon");
entry("psinfo");
entry("suspend");
entry("resume");
entry("ccreate");
entry("cstart");
entry("cfork");
entry("cstop");
entry("cpause");
entry("cresume");
entry("cinfo");
entry("df");
entry("cfree");
entry("setmaxcmem");
entry("setmaxcdsk");
entry("setmaxcproc");
entry("getticks");